mockserver.maxJsonStringLength=10000000
mockserver.maxExpectations=2000
mockserver.enableCORSForAllResponses=true
mockserver.corsAllowHeaders=Allow,Content-Encoding,Content-Length,Content-Type,ETag,Expires,Last-Modified,Location,Server,Vary,Authorization
mockserver.corsAllowMethods=CONNECT,DELETE,GET,HEAD,OPTIONS,POST,PUT,PATCH,TRACE
mockserver.corsAllowCredentials=true
mockserver.initializationJsonPath=/config/initializerJson.json
