// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateConversationsByAgent = `-- name: AggregateConversationsByAgent :many
SELECT assigned_member_id, COUNT(*) AS count
FROM conversations
WHERE tenant_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY assigned_member_id
`

type AggregateConversationsByAgentParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateConversationsByAgentRow struct {
	AssignedMemberID pgtype.UUID `json:"assigned_member_id"`
	Count            int64       `json:"count"`
}

func (q *Queries) AggregateConversationsByAgent(ctx context.Context, arg AggregateConversationsByAgentParams) ([]AggregateConversationsByAgentRow, error) {
	rows, err := q.db.Query(ctx, aggregateConversationsByAgent, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateConversationsByAgentRow{}
	for rows.Next() {
		var i AggregateConversationsByAgentRow
		if err := rows.Scan(&i.AssignedMemberID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateConversationsByChannel = `-- name: AggregateConversationsByChannel :many
SELECT c.channel_type, cv.status, COUNT(DISTINCT cv.id) AS count
FROM conversations cv
JOIN messages m ON m.conversation_id = cv.id AND m.tenant_id = cv.tenant_id
JOIN channels c ON c.id = m.channel_id
WHERE cv.tenant_id = $1 AND cv.created_at >= $2 AND cv.created_at < $3
GROUP BY c.channel_type, cv.status
`

type AggregateConversationsByChannelParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateConversationsByChannelRow struct {
	ChannelType string             `json:"channel_type"`
	Status      ConversationStatus `json:"status"`
	Count       int64              `json:"count"`
}

func (q *Queries) AggregateConversationsByChannel(ctx context.Context, arg AggregateConversationsByChannelParams) ([]AggregateConversationsByChannelRow, error) {
	rows, err := q.db.Query(ctx, aggregateConversationsByChannel, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateConversationsByChannelRow{}
	for rows.Next() {
		var i AggregateConversationsByChannelRow
		if err := rows.Scan(&i.ChannelType, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateConversationsByHandledBy = `-- name: AggregateConversationsByHandledBy :many
SELECT handled_by, COUNT(*) AS count
FROM conversations
WHERE tenant_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY handled_by
`

type AggregateConversationsByHandledByParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateConversationsByHandledByRow struct {
	HandledBy HandledBy `json:"handled_by"`
	Count     int64     `json:"count"`
}

func (q *Queries) AggregateConversationsByHandledBy(ctx context.Context, arg AggregateConversationsByHandledByParams) ([]AggregateConversationsByHandledByRow, error) {
	rows, err := q.db.Query(ctx, aggregateConversationsByHandledBy, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateConversationsByHandledByRow{}
	for rows.Next() {
		var i AggregateConversationsByHandledByRow
		if err := rows.Scan(&i.HandledBy, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateConversationsByStatus = `-- name: AggregateConversationsByStatus :many
SELECT status, COUNT(*) AS count
FROM conversations
WHERE tenant_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY status
`

type AggregateConversationsByStatusParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateConversationsByStatusRow struct {
	Status ConversationStatus `json:"status"`
	Count  int64              `json:"count"`
}

func (q *Queries) AggregateConversationsByStatus(ctx context.Context, arg AggregateConversationsByStatusParams) ([]AggregateConversationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, aggregateConversationsByStatus, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateConversationsByStatusRow{}
	for rows.Next() {
		var i AggregateConversationsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateConversationsTotalByChannel = `-- name: AggregateConversationsTotalByChannel :many
SELECT c.channel_type, COUNT(DISTINCT cv.id) AS count
FROM conversations cv
JOIN messages m ON m.conversation_id = cv.id AND m.tenant_id = cv.tenant_id
JOIN channels c ON c.id = m.channel_id
WHERE cv.tenant_id = $1 AND cv.created_at >= $2 AND cv.created_at < $3
GROUP BY c.channel_type
`

type AggregateConversationsTotalByChannelParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateConversationsTotalByChannelRow struct {
	ChannelType string `json:"channel_type"`
	Count       int64  `json:"count"`
}

func (q *Queries) AggregateConversationsTotalByChannel(ctx context.Context, arg AggregateConversationsTotalByChannelParams) ([]AggregateConversationsTotalByChannelRow, error) {
	rows, err := q.db.Query(ctx, aggregateConversationsTotalByChannel, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateConversationsTotalByChannelRow{}
	for rows.Next() {
		var i AggregateConversationsTotalByChannelRow
		if err := rows.Scan(&i.ChannelType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateMessagesByChannel = `-- name: AggregateMessagesByChannel :many
SELECT direction, c.channel_type, COUNT(*) AS count
FROM messages m
JOIN channels c ON c.id = m.channel_id
WHERE m.tenant_id = $1 AND m.created_at >= $2 AND m.created_at < $3
GROUP BY m.direction, c.channel_type
`

type AggregateMessagesByChannelParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateMessagesByChannelRow struct {
	Direction   MessageDirection `json:"direction"`
	ChannelType string           `json:"channel_type"`
	Count       int64            `json:"count"`
}

func (q *Queries) AggregateMessagesByChannel(ctx context.Context, arg AggregateMessagesByChannelParams) ([]AggregateMessagesByChannelRow, error) {
	rows, err := q.db.Query(ctx, aggregateMessagesByChannel, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateMessagesByChannelRow{}
	for rows.Next() {
		var i AggregateMessagesByChannelRow
		if err := rows.Scan(&i.Direction, &i.ChannelType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateMessagesByDirection = `-- name: AggregateMessagesByDirection :many
SELECT direction, COUNT(*) AS count
FROM messages
WHERE tenant_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY direction
`

type AggregateMessagesByDirectionParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateMessagesByDirectionRow struct {
	Direction MessageDirection `json:"direction"`
	Count     int64            `json:"count"`
}

func (q *Queries) AggregateMessagesByDirection(ctx context.Context, arg AggregateMessagesByDirectionParams) ([]AggregateMessagesByDirectionRow, error) {
	rows, err := q.db.Query(ctx, aggregateMessagesByDirection, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateMessagesByDirectionRow{}
	for rows.Next() {
		var i AggregateMessagesByDirectionRow
		if err := rows.Scan(&i.Direction, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aggregateMessagesTotalByChannel = `-- name: AggregateMessagesTotalByChannel :many
SELECT c.channel_type, COUNT(*) AS count
FROM messages m
JOIN channels c ON c.id = m.channel_id
WHERE m.tenant_id = $1 AND m.created_at >= $2 AND m.created_at < $3
GROUP BY c.channel_type
`

type AggregateMessagesTotalByChannelParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

type AggregateMessagesTotalByChannelRow struct {
	ChannelType string `json:"channel_type"`
	Count       int64  `json:"count"`
}

func (q *Queries) AggregateMessagesTotalByChannel(ctx context.Context, arg AggregateMessagesTotalByChannelParams) ([]AggregateMessagesTotalByChannelRow, error) {
	rows, err := q.db.Query(ctx, aggregateMessagesTotalByChannel, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateMessagesTotalByChannelRow{}
	for rows.Next() {
		var i AggregateMessagesTotalByChannelRow
		if err := rows.Scan(&i.ChannelType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsConversationsByStatus = `-- name: GetAnalyticsConversationsByStatus :many
SELECT metric_type, channel_type, SUM(value)::double precision AS total_value
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3 AND metric_type LIKE 'conversations_%'
GROUP BY metric_type, channel_type
ORDER BY metric_type, channel_type
`

type GetAnalyticsConversationsByStatusParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type GetAnalyticsConversationsByStatusRow struct {
	MetricType  string      `json:"metric_type"`
	ChannelType pgtype.Text `json:"channel_type"`
	TotalValue  float64     `json:"total_value"`
}

func (q *Queries) GetAnalyticsConversationsByStatus(ctx context.Context, arg GetAnalyticsConversationsByStatusParams) ([]GetAnalyticsConversationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsConversationsByStatus, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsConversationsByStatusRow{}
	for rows.Next() {
		var i GetAnalyticsConversationsByStatusRow
		if err := rows.Scan(&i.MetricType, &i.ChannelType, &i.TotalValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsDailyByTenantAndDateRange = `-- name: GetAnalyticsDailyByTenantAndDateRange :many
SELECT id, tenant_id, date, channel_type, metric_type, value, created_at, updated_at
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3
ORDER BY date ASC, metric_type ASC
`

type GetAnalyticsDailyByTenantAndDateRangeParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) GetAnalyticsDailyByTenantAndDateRange(ctx context.Context, arg GetAnalyticsDailyByTenantAndDateRangeParams) ([]AnalyticsDaily, error) {
	rows, err := q.db.Query(ctx, getAnalyticsDailyByTenantAndDateRange, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDaily{}
	for rows.Next() {
		var i AnalyticsDaily
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.ChannelType,
			&i.MetricType,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsDailyByTenantDateRangeAndChannel = `-- name: GetAnalyticsDailyByTenantDateRangeAndChannel :many
SELECT id, tenant_id, date, channel_type, metric_type, value, created_at, updated_at
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3 AND channel_type = $4
ORDER BY date ASC, metric_type ASC
`

type GetAnalyticsDailyByTenantDateRangeAndChannelParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	Date        pgtype.Date `json:"date"`
	Date_2      pgtype.Date `json:"date_2"`
	ChannelType pgtype.Text `json:"channel_type"`
}

func (q *Queries) GetAnalyticsDailyByTenantDateRangeAndChannel(ctx context.Context, arg GetAnalyticsDailyByTenantDateRangeAndChannelParams) ([]AnalyticsDaily, error) {
	rows, err := q.db.Query(ctx, getAnalyticsDailyByTenantDateRangeAndChannel,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.ChannelType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDaily{}
	for rows.Next() {
		var i AnalyticsDaily
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.ChannelType,
			&i.MetricType,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsDailyByTenantDateRangeAndMetric = `-- name: GetAnalyticsDailyByTenantDateRangeAndMetric :many
SELECT id, tenant_id, date, channel_type, metric_type, value, created_at, updated_at
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3 AND metric_type = $4
ORDER BY date ASC
`

type GetAnalyticsDailyByTenantDateRangeAndMetricParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Date       pgtype.Date `json:"date"`
	Date_2     pgtype.Date `json:"date_2"`
	MetricType string      `json:"metric_type"`
}

func (q *Queries) GetAnalyticsDailyByTenantDateRangeAndMetric(ctx context.Context, arg GetAnalyticsDailyByTenantDateRangeAndMetricParams) ([]AnalyticsDaily, error) {
	rows, err := q.db.Query(ctx, getAnalyticsDailyByTenantDateRangeAndMetric,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.MetricType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDaily{}
	for rows.Next() {
		var i AnalyticsDaily
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.ChannelType,
			&i.MetricType,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsOverview = `-- name: GetAnalyticsOverview :many
SELECT metric_type, SUM(value)::double precision AS total_value
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3
GROUP BY metric_type
ORDER BY metric_type
`

type GetAnalyticsOverviewParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type GetAnalyticsOverviewRow struct {
	MetricType string  `json:"metric_type"`
	TotalValue float64 `json:"total_value"`
}

func (q *Queries) GetAnalyticsOverview(ctx context.Context, arg GetAnalyticsOverviewParams) ([]GetAnalyticsOverviewRow, error) {
	rows, err := q.db.Query(ctx, getAnalyticsOverview, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAnalyticsOverviewRow{}
	for rows.Next() {
		var i GetAnalyticsOverviewRow
		if err := rows.Scan(&i.MetricType, &i.TotalValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageVolumeByDate = `-- name: GetMessageVolumeByDate :many
SELECT date, channel_type, metric_type, value
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3 AND metric_type IN ('messages_inbound', 'messages_outbound')
ORDER BY date ASC, channel_type ASC
`

type GetMessageVolumeByDateParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

type GetMessageVolumeByDateRow struct {
	Date        pgtype.Date `json:"date"`
	ChannelType pgtype.Text `json:"channel_type"`
	MetricType  string      `json:"metric_type"`
	Value       float64     `json:"value"`
}

func (q *Queries) GetMessageVolumeByDate(ctx context.Context, arg GetMessageVolumeByDateParams) ([]GetMessageVolumeByDateRow, error) {
	rows, err := q.db.Query(ctx, getMessageVolumeByDate, arg.TenantID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessageVolumeByDateRow{}
	for rows.Next() {
		var i GetMessageVolumeByDateRow
		if err := rows.Scan(
			&i.Date,
			&i.ChannelType,
			&i.MetricType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageVolumeCursor = `-- name: GetMessageVolumeCursor :many
SELECT id, tenant_id, date, channel_type, metric_type, value, created_at, updated_at
FROM analytics_daily
WHERE tenant_id = $1 AND date >= $2 AND date <= $3 AND metric_type IN ('messages_inbound', 'messages_outbound')
AND id > $4
ORDER BY id ASC LIMIT $5
`

type GetMessageVolumeCursorParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
	ID       uuid.UUID   `json:"id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) GetMessageVolumeCursor(ctx context.Context, arg GetMessageVolumeCursorParams) ([]AnalyticsDaily, error) {
	rows, err := q.db.Query(ctx, getMessageVolumeCursor,
		arg.TenantID,
		arg.Date,
		arg.Date_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnalyticsDaily{}
	for rows.Next() {
		var i AnalyticsDaily
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.ChannelType,
			&i.MetricType,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, mode, created_at, updated_at FROM tenants ORDER BY id
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnalyticsDaily = `-- name: UpsertAnalyticsDaily :exec
INSERT INTO analytics_daily (tenant_id, date, channel_type, metric_type, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, date, channel_type, metric_type)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type UpsertAnalyticsDailyParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	Date        pgtype.Date `json:"date"`
	ChannelType pgtype.Text `json:"channel_type"`
	MetricType  string      `json:"metric_type"`
	Value       float64     `json:"value"`
}

func (q *Queries) UpsertAnalyticsDaily(ctx context.Context, arg UpsertAnalyticsDailyParams) error {
	_, err := q.db.Exec(ctx, upsertAnalyticsDaily,
		arg.TenantID,
		arg.Date,
		arg.ChannelType,
		arg.MetricType,
		arg.Value,
	)
	return err
}
