// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAutomationsByTenant = `-- name: CountAutomationsByTenant :one
SELECT COUNT(*) FROM automations WHERE tenant_id = $1
`

func (q *Queries) CountAutomationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAutomationsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (tenant_id, name, status, definition)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, status, definition, created_at, updated_at
`

type CreateAutomationParams struct {
	TenantID   uuid.UUID        `json:"tenant_id"`
	Name       string           `json:"name"`
	Status     AutomationStatus `json:"status"`
	Definition []byte           `json:"definition"`
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.TenantID,
		arg.Name,
		arg.Status,
		arg.Definition,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO automation_runs (automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
`

type CreateAutomationRunParams struct {
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
}

type CreateAutomationRunRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (CreateAutomationRunRow, error) {
	row := q.db.QueryRow(ctx, createAutomationRun,
		arg.AutomationID,
		arg.TenantID,
		arg.ConversationID,
		arg.TriggerMessageID,
		arg.Status,
		arg.CurrentNodeID,
		arg.Variables,
	)
	var i CreateAutomationRunRow
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.CurrentNodeID,
		&i.Variables,
		&i.ResumeAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAutomation = `-- name: DeleteAutomation :exec
DELETE FROM automations WHERE id = $1 AND tenant_id = $2
`

type DeleteAutomationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAutomation(ctx context.Context, arg DeleteAutomationParams) error {
	_, err := q.db.Exec(ctx, deleteAutomation, arg.ID, arg.TenantID)
	return err
}

const getAutomationByID = `-- name: GetAutomationByID :one
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE id = $1 AND tenant_id = $2
`

type GetAutomationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAutomationByID(ctx context.Context, arg GetAutomationByIDParams) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomationByID, arg.ID, arg.TenantID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutomationRunByID = `-- name: GetAutomationRunByID :one
SELECT id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
FROM automation_runs WHERE id = $1
`

type GetAutomationRunByIDRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) GetAutomationRunByID(ctx context.Context, id uuid.UUID) (GetAutomationRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getAutomationRunByID, id)
	var i GetAutomationRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.CurrentNodeID,
		&i.Variables,
		&i.ResumeAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWaitingRunsByConversation = `-- name: GetWaitingRunsByConversation :many
SELECT id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
FROM automation_runs
WHERE conversation_id = $1 AND status = 'waiting'
`

type GetWaitingRunsByConversationRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) GetWaitingRunsByConversation(ctx context.Context, conversationID pgtype.UUID) ([]GetWaitingRunsByConversationRow, error) {
	rows, err := q.db.Query(ctx, getWaitingRunsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWaitingRunsByConversationRow{}
	for rows.Next() {
		var i GetWaitingRunsByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.TenantID,
			&i.ConversationID,
			&i.TriggerMessageID,
			&i.Status,
			&i.CurrentNodeID,
			&i.Variables,
			&i.ResumeAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAutomationsByTenant = `-- name: ListActiveAutomationsByTenant :many
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveAutomationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listActiveAutomationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRunsByAutomation = `-- name: ListAutomationRunsByAutomation :many
SELECT id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
FROM automation_runs WHERE automation_id = $1
ORDER BY started_at DESC
`

type ListAutomationRunsByAutomationRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) ListAutomationRunsByAutomation(ctx context.Context, automationID uuid.UUID) ([]ListAutomationRunsByAutomationRow, error) {
	rows, err := q.db.Query(ctx, listAutomationRunsByAutomation, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutomationRunsByAutomationRow{}
	for rows.Next() {
		var i ListAutomationRunsByAutomationRow
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.TenantID,
			&i.ConversationID,
			&i.TriggerMessageID,
			&i.Status,
			&i.CurrentNodeID,
			&i.Variables,
			&i.ResumeAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationsByTenant = `-- name: ListAutomationsByTenant :many
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE tenant_id = $1
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListAutomationsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAutomationsByTenant(ctx context.Context, arg ListAutomationsByTenantParams) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listAutomationsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollAutomationRunsForResume = `-- name: PollAutomationRunsForResume :many
SELECT id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
FROM automation_runs
WHERE status IN ('paused', 'waiting') AND resume_at <= now()
ORDER BY resume_at ASC
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type PollAutomationRunsForResumeRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) PollAutomationRunsForResume(ctx context.Context, limit int32) ([]PollAutomationRunsForResumeRow, error) {
	rows, err := q.db.Query(ctx, pollAutomationRunsForResume, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollAutomationRunsForResumeRow{}
	for rows.Next() {
		var i PollAutomationRunsForResumeRow
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.TenantID,
			&i.ConversationID,
			&i.TriggerMessageID,
			&i.Status,
			&i.CurrentNodeID,
			&i.Variables,
			&i.ResumeAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomation = `-- name: UpdateAutomation :one
UPDATE automations SET
    name = $1,
    status = $2,
    definition = $3,
    updated_at = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, name, status, definition, created_at, updated_at
`

type UpdateAutomationParams struct {
	Name       string           `json:"name"`
	Status     AutomationStatus `json:"status"`
	Definition []byte           `json:"definition"`
	ID         uuid.UUID        `json:"id"`
	TenantID   uuid.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, updateAutomation,
		arg.Name,
		arg.Status,
		arg.Definition,
		arg.ID,
		arg.TenantID,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutomationRunState = `-- name: UpdateAutomationRunState :one
UPDATE automation_runs SET
    status = $1,
    current_node_id = $2,
    variables = $3,
    resume_at = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
`

type UpdateAutomationRunStateParams struct {
	Status        AutomationRunStatus `json:"status"`
	CurrentNodeID pgtype.Text         `json:"current_node_id"`
	Variables     []byte              `json:"variables"`
	ResumeAt      pgtype.Timestamptz  `json:"resume_at"`
	ID            uuid.UUID           `json:"id"`
}

type UpdateAutomationRunStateRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) UpdateAutomationRunState(ctx context.Context, arg UpdateAutomationRunStateParams) (UpdateAutomationRunStateRow, error) {
	row := q.db.QueryRow(ctx, updateAutomationRunState,
		arg.Status,
		arg.CurrentNodeID,
		arg.Variables,
		arg.ResumeAt,
		arg.ID,
	)
	var i UpdateAutomationRunStateRow
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.CurrentNodeID,
		&i.Variables,
		&i.ResumeAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutomationRunStatus = `-- name: UpdateAutomationRunStatus :one
UPDATE automation_runs SET status = $1, completed_at = now(), updated_at = now()
WHERE id = $2
RETURNING id, automation_id, tenant_id, conversation_id, trigger_message_id, status, current_node_id, variables, resume_at, started_at, completed_at, updated_at
`

type UpdateAutomationRunStatusParams struct {
	Status AutomationRunStatus `json:"status"`
	ID     uuid.UUID           `json:"id"`
}

type UpdateAutomationRunStatusRow struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

func (q *Queries) UpdateAutomationRunStatus(ctx context.Context, arg UpdateAutomationRunStatusParams) (UpdateAutomationRunStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAutomationRunStatus, arg.Status, arg.ID)
	var i UpdateAutomationRunStatusRow
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.CurrentNodeID,
		&i.Variables,
		&i.ResumeAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
