// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAutomationsByTenant = `-- name: CountAutomationsByTenant :one
SELECT COUNT(*) FROM automations WHERE tenant_id = $1
`

func (q *Queries) CountAutomationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAutomationsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAutomation = `-- name: CreateAutomation :one
INSERT INTO automations (tenant_id, name, status, definition)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, status, definition, created_at, updated_at
`

type CreateAutomationParams struct {
	TenantID   uuid.UUID        `json:"tenant_id"`
	Name       string           `json:"name"`
	Status     AutomationStatus `json:"status"`
	Definition []byte           `json:"definition"`
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.TenantID,
		arg.Name,
		arg.Status,
		arg.Definition,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAutomationRun = `-- name: CreateAutomationRun :one
INSERT INTO automation_runs (automation_id, tenant_id, conversation_id, trigger_message_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, automation_id, tenant_id, conversation_id, trigger_message_id, status, started_at, completed_at
`

type CreateAutomationRunParams struct {
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
}

func (q *Queries) CreateAutomationRun(ctx context.Context, arg CreateAutomationRunParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, createAutomationRun,
		arg.AutomationID,
		arg.TenantID,
		arg.ConversationID,
		arg.TriggerMessageID,
		arg.Status,
	)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteAutomation = `-- name: DeleteAutomation :exec
DELETE FROM automations WHERE id = $1 AND tenant_id = $2
`

type DeleteAutomationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAutomation(ctx context.Context, arg DeleteAutomationParams) error {
	_, err := q.db.Exec(ctx, deleteAutomation, arg.ID, arg.TenantID)
	return err
}

const getAutomationByID = `-- name: GetAutomationByID :one
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE id = $1 AND tenant_id = $2
`

type GetAutomationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAutomationByID(ctx context.Context, arg GetAutomationByIDParams) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomationByID, arg.ID, arg.TenantID)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAutomationsByTenant = `-- name: ListActiveAutomationsByTenant :many
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE tenant_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveAutomationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listActiveAutomationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationRunsByAutomation = `-- name: ListAutomationRunsByAutomation :many
SELECT id, automation_id, tenant_id, conversation_id, trigger_message_id, status, started_at, completed_at
FROM automation_runs WHERE automation_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListAutomationRunsByAutomation(ctx context.Context, automationID uuid.UUID) ([]AutomationRun, error) {
	rows, err := q.db.Query(ctx, listAutomationRunsByAutomation, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutomationRun{}
	for rows.Next() {
		var i AutomationRun
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.TenantID,
			&i.ConversationID,
			&i.TriggerMessageID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationsByTenant = `-- name: ListAutomationsByTenant :many
SELECT id, tenant_id, name, status, definition, created_at, updated_at
FROM automations WHERE tenant_id = $1
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListAutomationsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListAutomationsByTenant(ctx context.Context, arg ListAutomationsByTenantParams) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listAutomationsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Automation{}
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomation = `-- name: UpdateAutomation :one
UPDATE automations SET
    name = $1,
    status = $2,
    definition = $3,
    updated_at = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, name, status, definition, created_at, updated_at
`

type UpdateAutomationParams struct {
	Name       string           `json:"name"`
	Status     AutomationStatus `json:"status"`
	Definition []byte           `json:"definition"`
	ID         uuid.UUID        `json:"id"`
	TenantID   uuid.UUID        `json:"tenant_id"`
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, updateAutomation,
		arg.Name,
		arg.Status,
		arg.Definition,
		arg.ID,
		arg.TenantID,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutomationRunStatus = `-- name: UpdateAutomationRunStatus :one
UPDATE automation_runs SET status = $1, completed_at = now()
WHERE id = $2
RETURNING id, automation_id, tenant_id, conversation_id, trigger_message_id, status, started_at, completed_at
`

type UpdateAutomationRunStatusParams struct {
	Status AutomationRunStatus `json:"status"`
	ID     uuid.UUID           `json:"id"`
}

func (q *Queries) UpdateAutomationRunStatus(ctx context.Context, arg UpdateAutomationRunStatusParams) (AutomationRun, error) {
	row := q.db.QueryRow(ctx, updateAutomationRunStatus, arg.Status, arg.ID)
	var i AutomationRun
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.TenantID,
		&i.ConversationID,
		&i.TriggerMessageID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
