// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcasts.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AddBroadcastRecipientsParams struct {
	BroadcastID uuid.UUID                `json:"broadcast_id"`
	ContactID   uuid.UUID                `json:"contact_id"`
	Status      BroadcastRecipientStatus `json:"status"`
}

const countBroadcastRecipients = `-- name: CountBroadcastRecipients :one
SELECT COUNT(*) FROM broadcast_recipients WHERE broadcast_id = $1
`

func (q *Queries) CountBroadcastRecipients(ctx context.Context, broadcastID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBroadcastRecipients, broadcastID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBroadcastRecipientsByStatus = `-- name: CountBroadcastRecipientsByStatus :one
SELECT COUNT(*) FROM broadcast_recipients WHERE broadcast_id = $1 AND status = $2
`

type CountBroadcastRecipientsByStatusParams struct {
	BroadcastID uuid.UUID                `json:"broadcast_id"`
	Status      BroadcastRecipientStatus `json:"status"`
}

func (q *Queries) CountBroadcastRecipientsByStatus(ctx context.Context, arg CountBroadcastRecipientsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBroadcastRecipientsByStatus, arg.BroadcastID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBroadcastsByTenant = `-- name: CountBroadcastsByTenant :one
SELECT COUNT(*) FROM broadcasts WHERE tenant_id = $1
`

func (q *Queries) CountBroadcastsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBroadcastsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBroadcast = `-- name: CreateBroadcast :one
INSERT INTO broadcasts (tenant_id, title, template_id, parameters, channel_id, status, scheduled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
`

type CreateBroadcastParams struct {
	TenantID    uuid.UUID          `json:"tenant_id"`
	Title       string             `json:"title"`
	TemplateID  pgtype.UUID        `json:"template_id"`
	Parameters  []byte             `json:"parameters"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	Status      BroadcastStatus    `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateBroadcast(ctx context.Context, arg CreateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, createBroadcast,
		arg.TenantID,
		arg.Title,
		arg.TemplateID,
		arg.Parameters,
		arg.ChannelID,
		arg.Status,
		arg.ScheduledAt,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.TemplateID,
		&i.Parameters,
		&i.ChannelID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBroadcast = `-- name: DeleteBroadcast :exec
DELETE FROM broadcasts WHERE id = $1 AND tenant_id = $2
`

type DeleteBroadcastParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteBroadcast(ctx context.Context, arg DeleteBroadcastParams) error {
	_, err := q.db.Exec(ctx, deleteBroadcast, arg.ID, arg.TenantID)
	return err
}

const findContactsByTag = `-- name: FindContactsByTag :many
SELECT c.id, c.tenant_id, c.name, c.email, c.language, c.created_at, c.updated_at
FROM contacts c
JOIN contact_tag_links l ON c.id = l.contact_id
JOIN contact_tags t ON l.tag_id = t.id
WHERE c.tenant_id = $1 AND t.name = $2
`

type FindContactsByTagParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

func (q *Queries) FindContactsByTag(ctx context.Context, arg FindContactsByTagParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, findContactsByTag, arg.TenantID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBroadcastByID = `-- name: GetBroadcastByID :one
SELECT id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
FROM broadcasts WHERE id = $1 AND tenant_id = $2
`

type GetBroadcastByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetBroadcastByID(ctx context.Context, arg GetBroadcastByIDParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcastByID, arg.ID, arg.TenantID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.TemplateID,
		&i.Parameters,
		&i.ChannelID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcastByIDForWorker = `-- name: GetBroadcastByIDForWorker :one
SELECT id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
FROM broadcasts WHERE id = $1
`

func (q *Queries) GetBroadcastByIDForWorker(ctx context.Context, id uuid.UUID) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcastByIDForWorker, id)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.TemplateID,
		&i.Parameters,
		&i.ChannelID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingRecipientsForBroadcast = `-- name: GetPendingRecipientsForBroadcast :many
SELECT r.id, r.broadcast_id, r.contact_id, r.status, r.sent_at, r.error, r.created_at,
       cp.phone as contact_phone
FROM broadcast_recipients r
JOIN contacts c ON r.contact_id = c.id
LEFT JOIN contact_phones cp ON cp.contact_id = c.id AND cp.label = 'primary'
WHERE r.broadcast_id = $1 AND r.status = 'pending'
ORDER BY r.created_at ASC
LIMIT $2
`

type GetPendingRecipientsForBroadcastParams struct {
	BroadcastID uuid.UUID `json:"broadcast_id"`
	Limit       int32     `json:"limit"`
}

type GetPendingRecipientsForBroadcastRow struct {
	ID           uuid.UUID                `json:"id"`
	BroadcastID  uuid.UUID                `json:"broadcast_id"`
	ContactID    uuid.UUID                `json:"contact_id"`
	Status       BroadcastRecipientStatus `json:"status"`
	SentAt       pgtype.Timestamptz       `json:"sent_at"`
	Error        pgtype.Text              `json:"error"`
	CreatedAt    time.Time                `json:"created_at"`
	ContactPhone pgtype.Text              `json:"contact_phone"`
}

func (q *Queries) GetPendingRecipientsForBroadcast(ctx context.Context, arg GetPendingRecipientsForBroadcastParams) ([]GetPendingRecipientsForBroadcastRow, error) {
	rows, err := q.db.Query(ctx, getPendingRecipientsForBroadcast, arg.BroadcastID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingRecipientsForBroadcastRow{}
	for rows.Next() {
		var i GetPendingRecipientsForBroadcastRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcastID,
			&i.ContactID,
			&i.Status,
			&i.SentAt,
			&i.Error,
			&i.CreatedAt,
			&i.ContactPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastRecipients = `-- name: ListBroadcastRecipients :many
SELECT r.id, r.broadcast_id, r.contact_id, r.status, r.sent_at, r.error, r.created_at,
       c.name as contact_name, cp.phone as contact_phone
FROM broadcast_recipients r
JOIN contacts c ON r.contact_id = c.id
LEFT JOIN contact_phones cp ON cp.contact_id = c.id AND cp.label = 'primary'
WHERE r.broadcast_id = $1
ORDER BY r.created_at ASC LIMIT $2 OFFSET $3
`

type ListBroadcastRecipientsParams struct {
	BroadcastID uuid.UUID `json:"broadcast_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

type ListBroadcastRecipientsRow struct {
	ID           uuid.UUID                `json:"id"`
	BroadcastID  uuid.UUID                `json:"broadcast_id"`
	ContactID    uuid.UUID                `json:"contact_id"`
	Status       BroadcastRecipientStatus `json:"status"`
	SentAt       pgtype.Timestamptz       `json:"sent_at"`
	Error        pgtype.Text              `json:"error"`
	CreatedAt    time.Time                `json:"created_at"`
	ContactName  pgtype.Text              `json:"contact_name"`
	ContactPhone pgtype.Text              `json:"contact_phone"`
}

func (q *Queries) ListBroadcastRecipients(ctx context.Context, arg ListBroadcastRecipientsParams) ([]ListBroadcastRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listBroadcastRecipients, arg.BroadcastID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBroadcastRecipientsRow{}
	for rows.Next() {
		var i ListBroadcastRecipientsRow
		if err := rows.Scan(
			&i.ID,
			&i.BroadcastID,
			&i.ContactID,
			&i.Status,
			&i.SentAt,
			&i.Error,
			&i.CreatedAt,
			&i.ContactName,
			&i.ContactPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBroadcastsByTenant = `-- name: ListBroadcastsByTenant :many
SELECT id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
FROM broadcasts WHERE tenant_id = $1
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListBroadcastsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBroadcastsByTenant(ctx context.Context, arg ListBroadcastsByTenantParams) ([]Broadcast, error) {
	rows, err := q.db.Query(ctx, listBroadcastsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcast{}
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.TemplateID,
			&i.Parameters,
			&i.ChannelID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledBroadcastsReady = `-- name: ListScheduledBroadcastsReady :many
SELECT id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
FROM broadcasts
WHERE status = 'scheduled' AND scheduled_at <= now()
ORDER BY scheduled_at ASC
`

func (q *Queries) ListScheduledBroadcastsReady(ctx context.Context) ([]Broadcast, error) {
	rows, err := q.db.Query(ctx, listScheduledBroadcastsReady)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcast{}
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.TemplateID,
			&i.Parameters,
			&i.ChannelID,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBroadcast = `-- name: UpdateBroadcast :one
UPDATE broadcasts SET
    title = $1,
    template_id = $2,
    parameters = $3,
    channel_id = $4,
    status = $5,
    scheduled_at = $6,
    updated_at = now()
WHERE id = $7 AND tenant_id = $8
RETURNING id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
`

type UpdateBroadcastParams struct {
	Title       string             `json:"title"`
	TemplateID  pgtype.UUID        `json:"template_id"`
	Parameters  []byte             `json:"parameters"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	Status      BroadcastStatus    `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateBroadcast(ctx context.Context, arg UpdateBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, updateBroadcast,
		arg.Title,
		arg.TemplateID,
		arg.Parameters,
		arg.ChannelID,
		arg.Status,
		arg.ScheduledAt,
		arg.ID,
		arg.TenantID,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.TemplateID,
		&i.Parameters,
		&i.ChannelID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBroadcastRecipientStatus = `-- name: UpdateBroadcastRecipientStatus :exec
UPDATE broadcast_recipients SET status = $1, sent_at = $2, error = $3 WHERE id = $4
`

type UpdateBroadcastRecipientStatusParams struct {
	Status BroadcastRecipientStatus `json:"status"`
	SentAt pgtype.Timestamptz       `json:"sent_at"`
	Error  pgtype.Text              `json:"error"`
	ID     uuid.UUID                `json:"id"`
}

func (q *Queries) UpdateBroadcastRecipientStatus(ctx context.Context, arg UpdateBroadcastRecipientStatusParams) error {
	_, err := q.db.Exec(ctx, updateBroadcastRecipientStatus,
		arg.Status,
		arg.SentAt,
		arg.Error,
		arg.ID,
	)
	return err
}

const updateBroadcastStatus = `-- name: UpdateBroadcastStatus :one
UPDATE broadcasts SET status = $1, started_at = $2, completed_at = $3, updated_at = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, title, template_id, parameters, channel_id, status, scheduled_at, started_at, completed_at, created_at, updated_at
`

type UpdateBroadcastStatusParams struct {
	Status      BroadcastStatus    `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateBroadcastStatus(ctx context.Context, arg UpdateBroadcastStatusParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, updateBroadcastStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
		arg.TenantID,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.TemplateID,
		&i.Parameters,
		&i.ChannelID,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
