// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (tenant_id, name, channel_type, config, status) VALUES ($1, $2, $3, $4, $5) RETURNING id, tenant_id, name, channel_type, config, status, created_at, updated_at
`

type CreateChannelParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
}

type CreateChannelRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (CreateChannelRow, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.TenantID,
		arg.Name,
		arg.ChannelType,
		arg.Config,
		arg.Status,
	)
	var i CreateChannelRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, tenant_id, name, channel_type, config, status, created_at, updated_at FROM channels WHERE id = $1
`

type GetChannelByIDRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetChannelByID(ctx context.Context, id uuid.UUID) (GetChannelByIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i GetChannelByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.Config,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelsByTenant = `-- name: ListChannelsByTenant :many
SELECT id, tenant_id, name, channel_type, config, status, created_at, updated_at FROM channels WHERE tenant_id = $1
`

type ListChannelsByTenantRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListChannelsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListChannelsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listChannelsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsByTenantRow{}
	for rows.Next() {
		var i ListChannelsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ChannelType,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByTenantAndType = `-- name: ListChannelsByTenantAndType :many
SELECT id, tenant_id, name, channel_type, config, status, created_at, updated_at FROM channels WHERE tenant_id = $1 AND channel_type = $2
`

type ListChannelsByTenantAndTypeParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	ChannelType string    `json:"channel_type"`
}

type ListChannelsByTenantAndTypeRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListChannelsByTenantAndType(ctx context.Context, arg ListChannelsByTenantAndTypeParams) ([]ListChannelsByTenantAndTypeRow, error) {
	rows, err := q.db.Query(ctx, listChannelsByTenantAndType, arg.TenantID, arg.ChannelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsByTenantAndTypeRow{}
	for rows.Next() {
		var i ListChannelsByTenantAndTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ChannelType,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
