// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countContactsByTenant = `-- name: CountContactsByTenant :one
SELECT COUNT(*) FROM contacts WHERE tenant_id = $1
`

func (q *Queries) CountContactsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContactsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelIdentity = `-- name: CreateChannelIdentity :one
INSERT INTO channel_identities (contact_id, channel_type, channel_identity) VALUES ($1, $2, $3) ON CONFLICT (contact_id, channel_type, channel_identity) DO NOTHING RETURNING id, contact_id, channel_type, channel_identity, created_at
`

type CreateChannelIdentityParams struct {
	ContactID       uuid.UUID `json:"contact_id"`
	ChannelType     string    `json:"channel_type"`
	ChannelIdentity string    `json:"channel_identity"`
}

func (q *Queries) CreateChannelIdentity(ctx context.Context, arg CreateChannelIdentityParams) (ChannelIdentity, error) {
	row := q.db.QueryRow(ctx, createChannelIdentity, arg.ContactID, arg.ChannelType, arg.ChannelIdentity)
	var i ChannelIdentity
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.ChannelType,
		&i.ChannelIdentity,
		&i.CreatedAt,
	)
	return i, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (tenant_id, name, email, language) VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, email, language, created_at, updated_at
`

type CreateContactParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Language pgtype.Text `json:"language"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.Language,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContactPhone = `-- name: CreateContactPhone :one
INSERT INTO contact_phones (contact_id, phone, label) VALUES ($1, $2, $3) ON CONFLICT (contact_id, phone) DO NOTHING RETURNING id, contact_id, phone, label, created_at
`

type CreateContactPhoneParams struct {
	ContactID uuid.UUID   `json:"contact_id"`
	Phone     string      `json:"phone"`
	Label     pgtype.Text `json:"label"`
}

func (q *Queries) CreateContactPhone(ctx context.Context, arg CreateContactPhoneParams) (ContactPhone, error) {
	row := q.db.QueryRow(ctx, createContactPhone, arg.ContactID, arg.Phone, arg.Label)
	var i ContactPhone
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Phone,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannelIdentitiesByContactID = `-- name: DeleteChannelIdentitiesByContactID :exec
DELETE FROM channel_identities WHERE contact_id = $1
`

func (q *Queries) DeleteChannelIdentitiesByContactID(ctx context.Context, contactID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannelIdentitiesByContactID, contactID)
	return err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts WHERE id = $1 AND tenant_id = $2
`

type DeleteContactParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.ID, arg.TenantID)
	return err
}

const deleteContactPhonesByContactID = `-- name: DeleteContactPhonesByContactID :exec
DELETE FROM contact_phones WHERE contact_id = $1
`

func (q *Queries) DeleteContactPhonesByContactID(ctx context.Context, contactID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContactPhonesByContactID, contactID)
	return err
}

const getContactByChannelIdentity = `-- name: GetContactByChannelIdentity :one
SELECT c.id, c.tenant_id, c.name, c.email, c.language, c.created_at, c.updated_at
FROM contacts c
JOIN channel_identities ci ON c.id = ci.contact_id
WHERE c.tenant_id = $1 AND ci.channel_type = $2 AND ci.channel_identity = $3
`

type GetContactByChannelIdentityParams struct {
	TenantID        uuid.UUID `json:"tenant_id"`
	ChannelType     string    `json:"channel_type"`
	ChannelIdentity string    `json:"channel_identity"`
}

func (q *Queries) GetContactByChannelIdentity(ctx context.Context, arg GetContactByChannelIdentityParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByChannelIdentity, arg.TenantID, arg.ChannelType, arg.ChannelIdentity)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, tenant_id, name, email, language, created_at, updated_at FROM contacts WHERE id = $1 AND tenant_id = $2
`

type GetContactByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetContactByID(ctx context.Context, arg GetContactByIDParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, arg.ID, arg.TenantID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContactByPhone = `-- name: GetContactByPhone :one
SELECT c.id, c.tenant_id, c.name, c.email, c.language, c.created_at, c.updated_at
FROM contacts c
JOIN contact_phones cp ON c.id = cp.contact_id
WHERE c.tenant_id = $1 AND cp.phone = $2
`

type GetContactByPhoneParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Phone    string    `json:"phone"`
}

func (q *Queries) GetContactByPhone(ctx context.Context, arg GetContactByPhoneParams) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByPhone, arg.TenantID, arg.Phone)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelIdentities = `-- name: ListChannelIdentities :many
SELECT id, contact_id, channel_type, channel_identity, created_at FROM channel_identities WHERE contact_id = $1
`

func (q *Queries) ListChannelIdentities(ctx context.Context, contactID uuid.UUID) ([]ChannelIdentity, error) {
	rows, err := q.db.Query(ctx, listChannelIdentities, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelIdentity{}
	for rows.Next() {
		var i ChannelIdentity
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.ChannelType,
			&i.ChannelIdentity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactPhones = `-- name: ListContactPhones :many
SELECT id, contact_id, phone, label, created_at FROM contact_phones WHERE contact_id = $1
`

func (q *Queries) ListContactPhones(ctx context.Context, contactID uuid.UUID) ([]ContactPhone, error) {
	rows, err := q.db.Query(ctx, listContactPhones, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContactPhone{}
	for rows.Next() {
		var i ContactPhone
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Phone,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByTenant = `-- name: ListContactsByTenant :many
SELECT id, tenant_id, name, email, language, created_at, updated_at FROM contacts WHERE tenant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListContactsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListContactsByTenant(ctx context.Context, arg ListContactsByTenantParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveChannelIdentities = `-- name: MoveChannelIdentities :exec
UPDATE channel_identities SET contact_id = $1 WHERE contact_id = $2
`

type MoveChannelIdentitiesParams struct {
	ContactID   uuid.UUID `json:"contact_id"`
	ContactID_2 uuid.UUID `json:"contact_id_2"`
}

func (q *Queries) MoveChannelIdentities(ctx context.Context, arg MoveChannelIdentitiesParams) error {
	_, err := q.db.Exec(ctx, moveChannelIdentities, arg.ContactID, arg.ContactID_2)
	return err
}

const moveContactPhones = `-- name: MoveContactPhones :exec
UPDATE contact_phones SET contact_id = $1 WHERE contact_id = $2
`

type MoveContactPhonesParams struct {
	ContactID   uuid.UUID `json:"contact_id"`
	ContactID_2 uuid.UUID `json:"contact_id_2"`
}

func (q *Queries) MoveContactPhones(ctx context.Context, arg MoveContactPhonesParams) error {
	_, err := q.db.Exec(ctx, moveContactPhones, arg.ContactID, arg.ContactID_2)
	return err
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts SET name = $1, email = $2, language = $3, updated_at = now() WHERE id = $4 AND tenant_id = $5 RETURNING id, tenant_id, name, email, language, created_at, updated_at
`

type UpdateContactParams struct {
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Language pgtype.Text `json:"language"`
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.Email,
		arg.Language,
		arg.ID,
		arg.TenantID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
