// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countConversationsByTenant = `-- name: CountConversationsByTenant :one
SELECT COUNT(*) FROM conversations WHERE tenant_id = $1
`

func (q *Queries) CountConversationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConversationsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessagesByConversation = `-- name: CountMessagesByConversation :one
SELECT COUNT(*) FROM messages WHERE conversation_id = $1 AND tenant_id = $2
`

type CountMessagesByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

func (q *Queries) CountMessagesByConversation(ctx context.Context, arg CountMessagesByConversationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesByConversation, arg.ConversationID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
`

type CreateConversationParams struct {
	TenantID               uuid.UUID          `json:"tenant_id"`
	ContactID              uuid.UUID          `json:"contact_id"`
	Status                 ConversationStatus `json:"status"`
	AssignedMemberID       pgtype.UUID        `json:"assigned_member_id"`
	HandledBy              HandledBy          `json:"handled_by"`
	PreviousConversationID pgtype.UUID        `json:"previous_conversation_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.TenantID,
		arg.ContactID,
		arg.Status,
		arg.AssignedMemberID,
		arg.HandledBy,
		arg.PreviousConversationID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Status,
		&i.AssignedMemberID,
		&i.HandledBy,
		&i.PreviousConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (tenant_id, conversation_id, channel_id, direction, status, content_type, content)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, conversation_id, channel_id, direction, status, content_type, content, created_at, updated_at
`

type CreateMessageParams struct {
	TenantID       uuid.UUID        `json:"tenant_id"`
	ConversationID uuid.UUID        `json:"conversation_id"`
	ChannelID      pgtype.UUID      `json:"channel_id"`
	Direction      MessageDirection `json:"direction"`
	Status         MessageStatus    `json:"status"`
	ContentType    string           `json:"content_type"`
	Content        []byte           `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.TenantID,
		arg.ConversationID,
		arg.ChannelID,
		arg.Direction,
		arg.Status,
		arg.ContentType,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.ChannelID,
		&i.Direction,
		&i.Status,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
FROM conversations WHERE id = $1 AND tenant_id = $2
`

type GetConversationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetConversationByID(ctx context.Context, arg GetConversationByIDParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, arg.ID, arg.TenantID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Status,
		&i.AssignedMemberID,
		&i.HandledBy,
		&i.PreviousConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastConversationByContact = `-- name: GetLastConversationByContact :one
SELECT id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
FROM conversations
WHERE tenant_id = $1 AND contact_id = $2
ORDER BY updated_at DESC LIMIT 1
`

type GetLastConversationByContactParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ContactID uuid.UUID `json:"contact_id"`
}

func (q *Queries) GetLastConversationByContact(ctx context.Context, arg GetLastConversationByContactParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getLastConversationByContact, arg.TenantID, arg.ContactID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Status,
		&i.AssignedMemberID,
		&i.HandledBy,
		&i.PreviousConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastMessageByConversation = `-- name: GetLastMessageByConversation :one
SELECT id, tenant_id, conversation_id, channel_id, direction, status, content_type, content, created_at, updated_at
FROM messages WHERE conversation_id = $1 AND direction = 'inbound'
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastMessageByConversation(ctx context.Context, conversationID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getLastMessageByConversation, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.ChannelID,
		&i.Direction,
		&i.Status,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, tenant_id, conversation_id, channel_id, direction, status, content_type, content, created_at, updated_at
FROM messages WHERE id = $1 AND tenant_id = $2
`

type GetMessageByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, arg.ID, arg.TenantID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.ChannelID,
		&i.Direction,
		&i.Status,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenConversationByContact = `-- name: GetOpenConversationByContact :one
SELECT id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
FROM conversations
WHERE tenant_id = $1 AND contact_id = $2 AND status != 'closed'
ORDER BY updated_at DESC LIMIT 1
`

type GetOpenConversationByContactParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ContactID uuid.UUID `json:"contact_id"`
}

func (q *Queries) GetOpenConversationByContact(ctx context.Context, arg GetOpenConversationByContactParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOpenConversationByContact, arg.TenantID, arg.ContactID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Status,
		&i.AssignedMemberID,
		&i.HandledBy,
		&i.PreviousConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByTenant = `-- name: ListConversationsByTenant :many
SELECT id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
FROM conversations WHERE tenant_id = $1
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListConversationsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListConversationsByTenant(ctx context.Context, arg ListConversationsByTenantParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ContactID,
			&i.Status,
			&i.AssignedMemberID,
			&i.HandledBy,
			&i.PreviousConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, tenant_id, conversation_id, channel_id, direction, status, content_type, content, created_at, updated_at
FROM messages WHERE conversation_id = $1 AND tenant_id = $2
ORDER BY created_at ASC LIMIT $3 OFFSET $4
`

type ListMessagesByConversationParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation,
		arg.ConversationID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ConversationID,
			&i.ChannelID,
			&i.Direction,
			&i.Status,
			&i.ContentType,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversation = `-- name: UpdateConversation :one
UPDATE conversations SET
    status = $1,
    assigned_member_id = $2,
    handled_by = $3,
    updated_at = now()
WHERE id = $4 AND tenant_id = $5
RETURNING id, tenant_id, contact_id, status, assigned_member_id, handled_by, previous_conversation_id, created_at, updated_at
`

type UpdateConversationParams struct {
	Status           ConversationStatus `json:"status"`
	AssignedMemberID pgtype.UUID        `json:"assigned_member_id"`
	HandledBy        HandledBy          `json:"handled_by"`
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, updateConversation,
		arg.Status,
		arg.AssignedMemberID,
		arg.HandledBy,
		arg.ID,
		arg.TenantID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ContactID,
		&i.Status,
		&i.AssignedMemberID,
		&i.HandledBy,
		&i.PreviousConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :one
UPDATE messages SET status = $1, updated_at = now()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, conversation_id, channel_id, direction, status, content_type, content, created_at, updated_at
`

type UpdateMessageStatusParams struct {
	Status   MessageStatus `json:"status"`
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.UUID     `json:"tenant_id"`
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageStatus, arg.Status, arg.ID, arg.TenantID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ConversationID,
		&i.ChannelID,
		&i.Direction,
		&i.Status,
		&i.ContentType,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
