// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForAddBroadcastRecipients implements pgx.CopyFromSource.
type iteratorForAddBroadcastRecipients struct {
	rows                 []AddBroadcastRecipientsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddBroadcastRecipients) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddBroadcastRecipients) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BroadcastID,
		r.rows[0].ContactID,
		r.rows[0].Status,
	}, nil
}

func (r iteratorForAddBroadcastRecipients) Err() error {
	return nil
}

// Recipients
func (q *Queries) AddBroadcastRecipients(ctx context.Context, arg []AddBroadcastRecipientsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"broadcast_recipients"}, []string{"broadcast_id", "contact_id", "status"}, &iteratorForAddBroadcastRecipients{rows: arg})
}
