// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1 AS healthy
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var healthy int32
	err := row.Scan(&healthy)
	return healthy, err
}
