// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AutomationRunStatus string

const (
	AutomationRunStatusRunning   AutomationRunStatus = "running"
	AutomationRunStatusCompleted AutomationRunStatus = "completed"
	AutomationRunStatusFailed    AutomationRunStatus = "failed"
	AutomationRunStatusPaused    AutomationRunStatus = "paused"
	AutomationRunStatusWaiting   AutomationRunStatus = "waiting"
)

func (e *AutomationRunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AutomationRunStatus(s)
	case string:
		*e = AutomationRunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AutomationRunStatus: %T", src)
	}
	return nil
}

type NullAutomationRunStatus struct {
	AutomationRunStatus AutomationRunStatus `json:"automation_run_status"`
	Valid               bool                `json:"valid"` // Valid is true if AutomationRunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAutomationRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AutomationRunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AutomationRunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAutomationRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AutomationRunStatus), nil
}

type AutomationStatus string

const (
	AutomationStatusDraft  AutomationStatus = "draft"
	AutomationStatusActive AutomationStatus = "active"
)

func (e *AutomationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AutomationStatus(s)
	case string:
		*e = AutomationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AutomationStatus: %T", src)
	}
	return nil
}

type NullAutomationStatus struct {
	AutomationStatus AutomationStatus `json:"automation_status"`
	Valid            bool             `json:"valid"` // Valid is true if AutomationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAutomationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AutomationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AutomationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAutomationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AutomationStatus), nil
}

type BroadcastRecipientStatus string

const (
	BroadcastRecipientStatusPending BroadcastRecipientStatus = "pending"
	BroadcastRecipientStatusSent    BroadcastRecipientStatus = "sent"
	BroadcastRecipientStatusFailed  BroadcastRecipientStatus = "failed"
)

func (e *BroadcastRecipientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BroadcastRecipientStatus(s)
	case string:
		*e = BroadcastRecipientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BroadcastRecipientStatus: %T", src)
	}
	return nil
}

type NullBroadcastRecipientStatus struct {
	BroadcastRecipientStatus BroadcastRecipientStatus `json:"broadcast_recipient_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if BroadcastRecipientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBroadcastRecipientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BroadcastRecipientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BroadcastRecipientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBroadcastRecipientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BroadcastRecipientStatus), nil
}

type BroadcastStatus string

const (
	BroadcastStatusDraft     BroadcastStatus = "draft"
	BroadcastStatusScheduled BroadcastStatus = "scheduled"
	BroadcastStatusSending   BroadcastStatus = "sending"
	BroadcastStatusCompleted BroadcastStatus = "completed"
	BroadcastStatusFailed    BroadcastStatus = "failed"
)

func (e *BroadcastStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BroadcastStatus(s)
	case string:
		*e = BroadcastStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BroadcastStatus: %T", src)
	}
	return nil
}

type NullBroadcastStatus struct {
	BroadcastStatus BroadcastStatus `json:"broadcast_status"`
	Valid           bool            `json:"valid"` // Valid is true if BroadcastStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBroadcastStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BroadcastStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BroadcastStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBroadcastStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BroadcastStatus), nil
}

type ConversationStatus string

const (
	ConversationStatusOpen      ConversationStatus = "open"
	ConversationStatusPending   ConversationStatus = "pending"
	ConversationStatusEscalated ConversationStatus = "escalated"
	ConversationStatusResolved  ConversationStatus = "resolved"
	ConversationStatusClosed    ConversationStatus = "closed"
)

func (e *ConversationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationStatus(s)
	case string:
		*e = ConversationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationStatus: %T", src)
	}
	return nil
}

type NullConversationStatus struct {
	ConversationStatus ConversationStatus `json:"conversation_status"`
	Valid              bool               `json:"valid"` // Valid is true if ConversationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationStatus), nil
}

type HandledBy string

const (
	HandledByAi     HandledBy = "ai"
	HandledByHuman  HandledBy = "human"
	HandledByHybrid HandledBy = "hybrid"
)

func (e *HandledBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandledBy(s)
	case string:
		*e = HandledBy(s)
	default:
		return fmt.Errorf("unsupported scan type for HandledBy: %T", src)
	}
	return nil
}

type NullHandledBy struct {
	HandledBy HandledBy `json:"handled_by"`
	Valid     bool      `json:"valid"` // Valid is true if HandledBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandledBy) Scan(value interface{}) error {
	if value == nil {
		ns.HandledBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandledBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandledBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandledBy), nil
}

type MessageDirection string

const (
	MessageDirectionInbound  MessageDirection = "inbound"
	MessageDirectionOutbound MessageDirection = "outbound"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection `json:"message_direction"`
	Valid            bool             `json:"valid"` // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

type MessageStatus string

const (
	MessageStatusPending   MessageStatus = "pending"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus `json:"message_status"`
	Valid         bool          `json:"valid"` // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type TemplateStatus string

const (
	TemplateStatusDraft    TemplateStatus = "draft"
	TemplateStatusPending  TemplateStatus = "pending"
	TemplateStatusApproved TemplateStatus = "approved"
	TemplateStatusRejected TemplateStatus = "rejected"
)

func (e *TemplateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateStatus(s)
	case string:
		*e = TemplateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateStatus: %T", src)
	}
	return nil
}

type NullTemplateStatus struct {
	TemplateStatus TemplateStatus `json:"template_status"`
	Valid          bool           `json:"valid"` // Valid is true if TemplateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateStatus), nil
}

type AnalyticsDaily struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Date        pgtype.Date `json:"date"`
	ChannelType pgtype.Text `json:"channel_type"`
	MetricType  string      `json:"metric_type"`
	Value       float64     `json:"value"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type Automation struct {
	ID         uuid.UUID        `json:"id"`
	TenantID   uuid.UUID        `json:"tenant_id"`
	Name       string           `json:"name"`
	Status     AutomationStatus `json:"status"`
	Definition []byte           `json:"definition"`
	CreatedAt  time.Time        `json:"created_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

type AutomationRun struct {
	ID               uuid.UUID           `json:"id"`
	AutomationID     uuid.UUID           `json:"automation_id"`
	TenantID         uuid.UUID           `json:"tenant_id"`
	ConversationID   pgtype.UUID         `json:"conversation_id"`
	TriggerMessageID pgtype.UUID         `json:"trigger_message_id"`
	Status           AutomationRunStatus `json:"status"`
	StartedAt        time.Time           `json:"started_at"`
	CompletedAt      pgtype.Timestamptz  `json:"completed_at"`
	CurrentNodeID    pgtype.Text         `json:"current_node_id"`
	Variables        []byte              `json:"variables"`
	ResumeAt         pgtype.Timestamptz  `json:"resume_at"`
	UpdatedAt        time.Time           `json:"updated_at"`
}

type Broadcast struct {
	ID          uuid.UUID          `json:"id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Title       string             `json:"title"`
	TemplateID  pgtype.UUID        `json:"template_id"`
	Parameters  []byte             `json:"parameters"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	Status      BroadcastStatus    `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type BroadcastRecipient struct {
	ID          uuid.UUID                `json:"id"`
	BroadcastID uuid.UUID                `json:"broadcast_id"`
	ContactID   uuid.UUID                `json:"contact_id"`
	Status      BroadcastRecipientStatus `json:"status"`
	SentAt      pgtype.Timestamptz       `json:"sent_at"`
	Error       pgtype.Text              `json:"error"`
	CreatedAt   time.Time                `json:"created_at"`
}

type Channel struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Name            string             `json:"name"`
	ChannelType     string             `json:"channel_type"`
	Config          []byte             `json:"config"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	HealthStatus    pgtype.Text        `json:"health_status"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
	LastError       pgtype.Text        `json:"last_error"`
}

type ChannelIdentity struct {
	ID              uuid.UUID `json:"id"`
	ContactID       uuid.UUID `json:"contact_id"`
	ChannelType     string    `json:"channel_type"`
	ChannelIdentity string    `json:"channel_identity"`
	CreatedAt       time.Time `json:"created_at"`
}

type Contact struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      pgtype.Text `json:"name"`
	Email     pgtype.Text `json:"email"`
	Language  pgtype.Text `json:"language"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ContactCustomField struct {
	ContactID uuid.UUID `json:"contact_id"`
	FieldID   uuid.UUID `json:"field_id"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ContactPhone struct {
	ID        uuid.UUID   `json:"id"`
	ContactID uuid.UUID   `json:"contact_id"`
	Phone     string      `json:"phone"`
	Label     pgtype.Text `json:"label"`
	CreatedAt time.Time   `json:"created_at"`
}

type ContactTag struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type ContactTagLink struct {
	ContactID uuid.UUID `json:"contact_id"`
	TagID     uuid.UUID `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Conversation struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	ContactID              uuid.UUID          `json:"contact_id"`
	Status                 ConversationStatus `json:"status"`
	AssignedMemberID       pgtype.UUID        `json:"assigned_member_id"`
	HandledBy              HandledBy          `json:"handled_by"`
	PreviousConversationID pgtype.UUID        `json:"previous_conversation_id"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type ConversationRead struct {
	ID             uuid.UUID `json:"id"`
	MemberID       uuid.UUID `json:"member_id"`
	ConversationID uuid.UUID `json:"conversation_id"`
	LastReadAt     time.Time `json:"last_read_at"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type CustomField struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	FieldType string    `json:"field_type"`
	Options   []byte    `json:"options"`
	CreatedAt time.Time `json:"created_at"`
}

type Member struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID        `json:"id"`
	TenantID       uuid.UUID        `json:"tenant_id"`
	ConversationID uuid.UUID        `json:"conversation_id"`
	ChannelID      pgtype.UUID      `json:"channel_id"`
	Direction      MessageDirection `json:"direction"`
	Status         MessageStatus    `json:"status"`
	ContentType    string           `json:"content_type"`
	Content        []byte           `json:"content"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	MemberID  uuid.UUID `json:"member_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SchedulerLock struct {
	ID        uuid.UUID `json:"id"`
	TaskName  string    `json:"task_name"`
	LockedAt  time.Time `json:"locked_at"`
	LockedBy  string    `json:"locked_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Template struct {
	ID               uuid.UUID      `json:"id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	ChannelID        pgtype.UUID    `json:"channel_id"`
	ParentTemplateID pgtype.UUID    `json:"parent_template_id"`
	Name             string         `json:"name"`
	Category         string         `json:"category"`
	Status           TemplateStatus `json:"status"`
	Language         string         `json:"language"`
	Body             string         `json:"body"`
	Parameters       []byte         `json:"parameters"`
	MetaTemplateID   pgtype.Text    `json:"meta_template_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Mode      string    `json:"mode"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WebhookEvent struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	ChannelID   pgtype.UUID `json:"channel_id"`
	ChannelType string      `json:"channel_type"`
	EventID     string      `json:"event_id"`
	RawPayload  []byte      `json:"raw_payload"`
	Processed   bool        `json:"processed"`
	CreatedAt   time.Time   `json:"created_at"`
}
