// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationStatus string

const (
	ConversationStatusOpen      ConversationStatus = "open"
	ConversationStatusPending   ConversationStatus = "pending"
	ConversationStatusEscalated ConversationStatus = "escalated"
	ConversationStatusResolved  ConversationStatus = "resolved"
	ConversationStatusClosed    ConversationStatus = "closed"
)

func (e *ConversationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConversationStatus(s)
	case string:
		*e = ConversationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConversationStatus: %T", src)
	}
	return nil
}

type NullConversationStatus struct {
	ConversationStatus ConversationStatus `json:"conversation_status"`
	Valid              bool               `json:"valid"` // Valid is true if ConversationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConversationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConversationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConversationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConversationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConversationStatus), nil
}

type HandledBy string

const (
	HandledByAi     HandledBy = "ai"
	HandledByHuman  HandledBy = "human"
	HandledByHybrid HandledBy = "hybrid"
)

func (e *HandledBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HandledBy(s)
	case string:
		*e = HandledBy(s)
	default:
		return fmt.Errorf("unsupported scan type for HandledBy: %T", src)
	}
	return nil
}

type NullHandledBy struct {
	HandledBy HandledBy `json:"handled_by"`
	Valid     bool      `json:"valid"` // Valid is true if HandledBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHandledBy) Scan(value interface{}) error {
	if value == nil {
		ns.HandledBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HandledBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHandledBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HandledBy), nil
}

type MessageDirection string

const (
	MessageDirectionInbound  MessageDirection = "inbound"
	MessageDirectionOutbound MessageDirection = "outbound"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection `json:"message_direction"`
	Valid            bool             `json:"valid"` // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

type MessageStatus string

const (
	MessageStatusPending   MessageStatus = "pending"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusRead      MessageStatus = "read"
	MessageStatusFailed    MessageStatus = "failed"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus `json:"message_status"`
	Valid         bool          `json:"valid"` // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type TemplateStatus string

const (
	TemplateStatusDraft    TemplateStatus = "draft"
	TemplateStatusPending  TemplateStatus = "pending"
	TemplateStatusApproved TemplateStatus = "approved"
	TemplateStatusRejected TemplateStatus = "rejected"
)

func (e *TemplateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TemplateStatus(s)
	case string:
		*e = TemplateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TemplateStatus: %T", src)
	}
	return nil
}

type NullTemplateStatus struct {
	TemplateStatus TemplateStatus `json:"template_status"`
	Valid          bool           `json:"valid"` // Valid is true if TemplateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTemplateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TemplateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TemplateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTemplateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TemplateStatus), nil
}

type Channel struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Name            string             `json:"name"`
	ChannelType     string             `json:"channel_type"`
	Config          []byte             `json:"config"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	HealthStatus    pgtype.Text        `json:"health_status"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
	LastError       pgtype.Text        `json:"last_error"`
}

type ChannelIdentity struct {
	ID              uuid.UUID `json:"id"`
	ContactID       uuid.UUID `json:"contact_id"`
	ChannelType     string    `json:"channel_type"`
	ChannelIdentity string    `json:"channel_identity"`
	CreatedAt       time.Time `json:"created_at"`
}

type Contact struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      pgtype.Text `json:"name"`
	Email     pgtype.Text `json:"email"`
	Language  pgtype.Text `json:"language"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type ContactPhone struct {
	ID        uuid.UUID   `json:"id"`
	ContactID uuid.UUID   `json:"contact_id"`
	Phone     string      `json:"phone"`
	Label     pgtype.Text `json:"label"`
	CreatedAt time.Time   `json:"created_at"`
}

type Conversation struct {
	ID                     uuid.UUID          `json:"id"`
	TenantID               uuid.UUID          `json:"tenant_id"`
	ContactID              uuid.UUID          `json:"contact_id"`
	Status                 ConversationStatus `json:"status"`
	AssignedMemberID       pgtype.UUID        `json:"assigned_member_id"`
	HandledBy              HandledBy          `json:"handled_by"`
	PreviousConversationID pgtype.UUID        `json:"previous_conversation_id"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

type Member struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Message struct {
	ID             uuid.UUID        `json:"id"`
	TenantID       uuid.UUID        `json:"tenant_id"`
	ConversationID uuid.UUID        `json:"conversation_id"`
	ChannelID      pgtype.UUID      `json:"channel_id"`
	Direction      MessageDirection `json:"direction"`
	Status         MessageStatus    `json:"status"`
	ContentType    string           `json:"content_type"`
	Content        []byte           `json:"content"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	MemberID  uuid.UUID `json:"member_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type SchedulerLock struct {
	ID        uuid.UUID `json:"id"`
	TaskName  string    `json:"task_name"`
	LockedAt  time.Time `json:"locked_at"`
	LockedBy  string    `json:"locked_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

type Template struct {
	ID               uuid.UUID      `json:"id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	ChannelID        pgtype.UUID    `json:"channel_id"`
	ParentTemplateID pgtype.UUID    `json:"parent_template_id"`
	Name             string         `json:"name"`
	Category         string         `json:"category"`
	Status           TemplateStatus `json:"status"`
	Language         string         `json:"language"`
	Body             string         `json:"body"`
	Parameters       []byte         `json:"parameters"`
	MetaTemplateID   pgtype.Text    `json:"meta_template_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Mode      string    `json:"mode"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WebhookEvent struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	ChannelID   pgtype.UUID `json:"channel_id"`
	ChannelType string      `json:"channel_type"`
	EventID     string      `json:"event_id"`
	RawPayload  []byte      `json:"raw_payload"`
	Processed   bool        `json:"processed"`
	CreatedAt   time.Time   `json:"created_at"`
}
