// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedulerLock = `-- name: CreateSchedulerLock :one
INSERT INTO scheduler_locks (task_name, locked_by, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (task_name) DO NOTHING
RETURNING id, task_name, locked_at, locked_by, expires_at
`

type CreateSchedulerLockParams struct {
	TaskName  string    `json:"task_name"`
	LockedBy  string    `json:"locked_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSchedulerLock(ctx context.Context, arg CreateSchedulerLockParams) (SchedulerLock, error) {
	row := q.db.QueryRow(ctx, createSchedulerLock, arg.TaskName, arg.LockedBy, arg.ExpiresAt)
	var i SchedulerLock
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.LockedAt,
		&i.LockedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSchedulerLock = `-- name: DeleteSchedulerLock :exec
DELETE FROM scheduler_locks WHERE task_name = $1 AND locked_by = $2
`

type DeleteSchedulerLockParams struct {
	TaskName string `json:"task_name"`
	LockedBy string `json:"locked_by"`
}

func (q *Queries) DeleteSchedulerLock(ctx context.Context, arg DeleteSchedulerLockParams) error {
	_, err := q.db.Exec(ctx, deleteSchedulerLock, arg.TaskName, arg.LockedBy)
	return err
}

const getChannelHealth = `-- name: GetChannelHealth :one
SELECT id, tenant_id, name, channel_type, health_status, health_checked_at, last_error FROM channels WHERE id = $1
`

type GetChannelHealthRow struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Name            string             `json:"name"`
	ChannelType     string             `json:"channel_type"`
	HealthStatus    pgtype.Text        `json:"health_status"`
	HealthCheckedAt pgtype.Timestamptz `json:"health_checked_at"`
	LastError       pgtype.Text        `json:"last_error"`
}

func (q *Queries) GetChannelHealth(ctx context.Context, id uuid.UUID) (GetChannelHealthRow, error) {
	row := q.db.QueryRow(ctx, getChannelHealth, id)
	var i GetChannelHealthRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ChannelType,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.LastError,
	)
	return i, err
}

const getSchedulerLock = `-- name: GetSchedulerLock :one
SELECT id, task_name, locked_at, locked_by, expires_at FROM scheduler_locks WHERE task_name = $1
`

func (q *Queries) GetSchedulerLock(ctx context.Context, taskName string) (SchedulerLock, error) {
	row := q.db.QueryRow(ctx, getSchedulerLock, taskName)
	var i SchedulerLock
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.LockedAt,
		&i.LockedBy,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveChannels = `-- name: ListActiveChannels :many
SELECT id, tenant_id, name, channel_type, config, status, created_at, updated_at FROM channels WHERE status = 'active'
`

type ListActiveChannelsRow struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	ChannelType string    `json:"channel_type"`
	Config      []byte    `json:"config"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListActiveChannels(ctx context.Context) ([]ListActiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, listActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveChannelsRow{}
	for rows.Next() {
		var i ListActiveChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ChannelType,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelHealth = `-- name: UpdateChannelHealth :exec
UPDATE channels SET health_status = $1, health_checked_at = now(), last_error = $2 WHERE id = $3
`

type UpdateChannelHealthParams struct {
	HealthStatus pgtype.Text `json:"health_status"`
	LastError    pgtype.Text `json:"last_error"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateChannelHealth(ctx context.Context, arg UpdateChannelHealthParams) error {
	_, err := q.db.Exec(ctx, updateChannelHealth, arg.HealthStatus, arg.LastError, arg.ID)
	return err
}

const updateSchedulerLock = `-- name: UpdateSchedulerLock :one
UPDATE scheduler_locks SET locked_by = $2, locked_at = now(), expires_at = $3
WHERE task_name = $1
RETURNING id, task_name, locked_at, locked_by, expires_at
`

type UpdateSchedulerLockParams struct {
	TaskName  string    `json:"task_name"`
	LockedBy  string    `json:"locked_by"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSchedulerLock(ctx context.Context, arg UpdateSchedulerLockParams) (SchedulerLock, error) {
	row := q.db.QueryRow(ctx, updateSchedulerLock, arg.TaskName, arg.LockedBy, arg.ExpiresAt)
	var i SchedulerLock
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.LockedAt,
		&i.LockedBy,
		&i.ExpiresAt,
	)
	return i, err
}
