// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTemplatesByTenant = `-- name: CountTemplatesByTenant :one
SELECT COUNT(*) FROM templates WHERE tenant_id = $1
`

func (q *Queries) CountTemplatesByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTemplatesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO templates (tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
`

type CreateTemplateParams struct {
	TenantID         uuid.UUID      `json:"tenant_id"`
	ChannelID        pgtype.UUID    `json:"channel_id"`
	ParentTemplateID pgtype.UUID    `json:"parent_template_id"`
	Name             string         `json:"name"`
	Category         string         `json:"category"`
	Status           TemplateStatus `json:"status"`
	Language         string         `json:"language"`
	Body             string         `json:"body"`
	Parameters       []byte         `json:"parameters"`
	MetaTemplateID   pgtype.Text    `json:"meta_template_id"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TenantID,
		arg.ChannelID,
		arg.ParentTemplateID,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.Language,
		arg.Body,
		arg.Parameters,
		arg.MetaTemplateID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelID,
		&i.ParentTemplateID,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.Language,
		&i.Body,
		&i.Parameters,
		&i.MetaTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE id = $1 AND tenant_id = $2
`

type DeleteTemplateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.TenantID)
	return err
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
FROM templates WHERE id = $1 AND tenant_id = $2
`

type GetTemplateByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID, arg.TenantID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelID,
		&i.ParentTemplateID,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.Language,
		&i.Body,
		&i.Parameters,
		&i.MetaTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTemplates = `-- name: ListPendingTemplates :many
SELECT id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
FROM templates WHERE status = 'pending'
`

func (q *Queries) ListPendingTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listPendingTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ParentTemplateID,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.Language,
			&i.Body,
			&i.Parameters,
			&i.MetaTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByTenant = `-- name: ListTemplatesByTenant :many
SELECT id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
FROM templates WHERE tenant_id = $1
ORDER BY updated_at DESC LIMIT $2 OFFSET $3
`

type ListTemplatesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTemplatesByTenant(ctx context.Context, arg ListTemplatesByTenantParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ParentTemplateID,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.Language,
			&i.Body,
			&i.Parameters,
			&i.MetaTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByTenantAndStatus = `-- name: ListTemplatesByTenantAndStatus :many
SELECT id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
FROM templates WHERE tenant_id = $1 AND status = $2
ORDER BY updated_at DESC
`

type ListTemplatesByTenantAndStatusParams struct {
	TenantID uuid.UUID      `json:"tenant_id"`
	Status   TemplateStatus `json:"status"`
}

func (q *Queries) ListTemplatesByTenantAndStatus(ctx context.Context, arg ListTemplatesByTenantAndStatusParams) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplatesByTenantAndStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Template{}
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ParentTemplateID,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.Language,
			&i.Body,
			&i.Parameters,
			&i.MetaTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET
    name = $1,
    category = $2,
    status = $3,
    language = $4,
    body = $5,
    parameters = $6,
    meta_template_id = $7,
    updated_at = now()
WHERE id = $8 AND tenant_id = $9
RETURNING id, tenant_id, channel_id, parent_template_id, name, category, status, language, body, parameters, meta_template_id, created_at, updated_at
`

type UpdateTemplateParams struct {
	Name           string         `json:"name"`
	Category       string         `json:"category"`
	Status         TemplateStatus `json:"status"`
	Language       string         `json:"language"`
	Body           string         `json:"body"`
	Parameters     []byte         `json:"parameters"`
	MetaTemplateID pgtype.Text    `json:"meta_template_id"`
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Category,
		arg.Status,
		arg.Language,
		arg.Body,
		arg.Parameters,
		arg.MetaTemplateID,
		arg.ID,
		arg.TenantID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelID,
		&i.ParentTemplateID,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.Language,
		&i.Body,
		&i.Parameters,
		&i.MetaTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
