// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (tenant_id, channel_id, channel_type, event_id, raw_payload) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (tenant_id, channel_type, event_id) DO NOTHING RETURNING id, tenant_id, channel_id, channel_type, event_id, raw_payload, processed, created_at
`

type CreateWebhookEventParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	ChannelID   pgtype.UUID `json:"channel_id"`
	ChannelType string      `json:"channel_type"`
	EventID     string      `json:"event_id"`
	RawPayload  []byte      `json:"raw_payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.TenantID,
		arg.ChannelID,
		arg.ChannelType,
		arg.EventID,
		arg.RawPayload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelID,
		&i.ChannelType,
		&i.EventID,
		&i.RawPayload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT id, tenant_id, channel_id, channel_type, event_id, raw_payload, processed, created_at FROM webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, id uuid.UUID) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChannelID,
		&i.ChannelType,
		&i.EventID,
		&i.RawPayload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedWebhookEvents = `-- name: ListUnprocessedWebhookEvents :many
SELECT id, tenant_id, channel_id, channel_type, event_id, raw_payload, processed, created_at FROM webhook_events WHERE processed = false ORDER BY created_at ASC LIMIT $1
`

func (q *Queries) ListUnprocessedWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ChannelType,
			&i.EventID,
			&i.RawPayload,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventProcessed = `-- name: MarkWebhookEventProcessed :exec
UPDATE webhook_events SET processed = true WHERE id = $1
`

func (q *Queries) MarkWebhookEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookEventProcessed, id)
	return err
}
